question_data = [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "In 2016, the United Kingdom voted to stay in the EU.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "Denmark has a monarch.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "Berlin was the capital of two countries for about 40 years.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "One of Donald Trump's 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "The S in Harry S. Truman stands for 'Samuel'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "One of Barack Obama's United States presidential campaign slogan's was 'Yes We Can'.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Politics",
            "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
]
